application: linux-1176
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fj
  static_dir: lib/fileuploader/js

- url: /fc
  static_dir: lib/fileuploader/css

- url: /img
  static_dir: img

- url: /.*
  script: _go_app